version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
      # Enable docker https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - echo ${SUB_FOLDER_NAME} ${SAM_TEMPLATE} ${TESTING_PIPELINE_EXECUTION_ROLE}
      - cd ${CODEBUILD_SRC_DIR_SourceCodeAsZipApp}
      - source ${CODEBUILD_SRC_DIR_SourceCodeAsZipApp}/config.env
      - env
      - ls -la
      - sam build --use-container --template ${CODEBUILD_SRC_DIR}/${RESOURCE_TYPE}-${SAM_TEMPLATE} --container-env-var SUB_FOLDER_NAME=${SUB_FOLDER_NAME} --parameter-overrides ParameterKey=SubFolderName,ParameterValue=${CODEBUILD_SRC_DIR_SourceCodeAsZipApp}/${SUB_FOLDER_NAME}
      - . ${CODEBUILD_SRC_DIR}/assume-role.sh ${TESTING_PIPELINE_EXECUTION_ROLE} test-package
      - sam package --s3-bucket ${TESTING_ARTIFACT_BUCKET}
                    --region ${TESTING_REGION}
                    --output-template-file packaged-test.yaml
      - . ${CODEBUILD_SRC_DIR}/assume-role.sh ${PROD_PIPELINE_EXECUTION_ROLE} prod-package
      - sam package --s3-bucket ${PROD_ARTIFACT_BUCKET}
                    --region ${PROD_REGION}
                    --output-template-file packaged-prod.yaml
      - ls -la
artifacts:
  type: zip
  base-directory: ${CODEBUILD_SRC_DIR_SourceCodeAsZipApp}
  files:
    - packaged-test.yaml
    - packaged-prod.yaml
