version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pipeline-trigger-vishwa"
s3_prefix = "pipeline-trigger-vishwa"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "cicd"
confirm_changeset = true
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6vvyn61bi2zg"
disable_rollback = true
parameter_overrides = "PipelineName=\"\" CodeStarConnectionArn=\"arn:aws:codestar-connections:us-east-1:731179564832:connection/4359bdf7-d1ff-4b5f-80fa-6be9d163b64a\""
