AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pipeline-trigger

  Sample SAM Template for pipeline-trigger

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  PipelineName:
    Type: String
    Description: The name of the pipeline to create
    Default: ""
  CodeStarConnectionArn:
    Type: String
    Default: "arn:aws:codestar-connections:us-east-1:731179564832:connection/4359bdf7-d1ff-4b5f-80fa-6be9d163b64a"

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Role
          Value: aws-sam-pipeline-codebuild-service-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
      Policies:
        - PolicyName: CodeBuildLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
        - PolicyName: CloudFormationAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudformation:*"
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*"
        - PolicyName: CreatePipelineResourcesAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "*"
#                  - "iam:*"
#                  - "s3:*"
#                  - "codestar-connections:*"
                Effect: Allow
                Resource: "*"
        - PolicyName: CreatePipeline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "codepipeline:CreatePipeline"
                Resource:
                  - "arn:aws:codepipeline:::*"
  PipelineTriggerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: handler/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
      - Statement:
        - Sid: PipelineTriggerPolicy
          Effect: Allow
          Action:
          - codepipeline:*
          - codebuild:*
          Resource: '*'
      Events:
        PipelineTrigger:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post
      Timeout: 900
  PipelineTriggerCreatePipelineTask:
    Type: AWS::CodeBuild::Project # More info about this Resource: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
    Properties:
      Name: create_pipeline
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ENV_PIPELINE_NAME
            Value: !Ref PipelineName
          - Name: ENV_CODESTAR_CONNECTION_ARN
            Value: !Ref CodeStarConnectionArn
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Type: GITHUB
        Location: https://github.com/lernae/sam-pipelines-devops-monorepo.git
        GitCloneDepth: 1
        BuildSpec: pipeline-trigger/buildspec_create_pipeline.yml
      SecondarySources:
        - Type: GITHUB
          Location: https://github.com/lernae/sam-pipelines-appdev-monorepo.git
          GitCloneDepth: 1
          SourceIdentifier: appdev

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PipelineTriggerApi:
    Description: "API Gateway endpoint URL for Prod stage for Pipeline Trigger function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
